// One-time seeders. Run the first time the server connects to an empty
// collection. Bets come from src/data/bets.ts; artifacts from the seed/
// folder (manifest + binaries), both regenerated by scripts/snapshot-seed.py.

import fs from 'node:fs'
import path from 'node:path'

import { Binary, type Collection, type Db } from 'mongodb'

import { SEED_BETS } from '../src/data/bets'
import type { Bet } from '../src/types/bet'

// __dirname only exists in CJS (vite dev); on Vercel (ESM) fall back to cwd.
const SEED_DIR_CANDIDATES = [
  ...(typeof __dirname !== 'undefined' ? [path.resolve(__dirname, '../seed')] : []),
  path.resolve(process.cwd(), 'seed')
]
const SEED_DIR = SEED_DIR_CANDIDATES.find((p) => fs.existsSync(p)) ?? SEED_DIR_CANDIDATES[0]

export async function seedIfEmpty(bets: Collection<Bet>): Promise<void> {
  const count = await bets.countDocuments()
  if (count > 0) return
  if (SEED_BETS.length === 0) return
  await bets.insertMany(SEED_BETS as Bet[])
  console.log(`[seed] inserted ${SEED_BETS.length} bet(s)`)
}

interface SeedArtifact {
  id: string
  betId: string
  name: string
  type?: string
  size: number
  uploadedAt: string
  file: string
}

export async function seedArtifactsIfEmpty(db: Db): Promise<void> {
  const col = db.collection('artifacts')
  if ((await col.countDocuments()) > 0) return
  const manifestPath = path.join(SEED_DIR, 'artifacts.json')
  if (!fs.existsSync(manifestPath)) return
  const manifest: SeedArtifact[] = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'))
  const docs = []
  for (const m of manifest) {
    const filePath = path.join(SEED_DIR, 'files', m.file)
    if (!fs.existsSync(filePath)) {
      console.warn(`[seed] missing artifact file: ${m.file}`)
      continue
    }
    const { file: _file, ...meta } = m
    docs.push({ ...meta, data: new Binary(fs.readFileSync(filePath)) })
  }
  if (docs.length === 0) return
  await col.insertMany(docs)
  console.log(`[seed] inserted ${docs.length} artifact(s)`)
}
